global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['app:3000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
rule_files:
  - "alerts.yml"
